version: '3.8'
services:
  mariadb:
    image: mariadb:11
    container_name: order-mariadb
    environment:
      MARIADB_DATABASE: order_db
      MARIADB_USER: order_user
      MARIADB_PASSWORD: order_pass
      MARIADB_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql

  redis:
    image: redis:7
    container_name: order-redis
    ports:
      - "6379:6379"