
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect